name: Deploy to Production [App]

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Build
        run: npm run test
        working-directory: ./app

  containerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ../../app/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/devops-app:v1

  deploy:
    runs-on: ubuntu-latest
    needs: containerize

    steps:
      - name: Deploy to Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            sudo docker stop devops-app || true
            sudo docker rm devops-app || true
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/devops-app:v1
            sudo docker run -d -p ${{secrets.EXPOSED_SERVER_PORT}}:${{secrets.IMAGE_SERVER_PORT}} ${{secrets.DOCKER_USERNAME}}/devops-app:v1
